### ISSUE TITLE
Connecting to Python from GH does not work on IronPython 2.7.0 (Rhino version)

### ISSUE THREAD

**Issue by pilcru** [Digital-Structures/ghpythonremote#6]
(From email, food4rhino)

This happens only when using the IronPython version included in Rhino (2.7.0), adding the IronPython 2.7.5 libraries to Rhino fixes the issue. When trying to connect, fails with:

```
10. Runtime error (MissingMemberException): 'module' object has no attribute 'async'

11. Traceback:

  line 117, in _get_connection, "C:\Users\Alex\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"

  line 36, in __init__, "C:\Users\Alex\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"

  line 49, in script
```

When the async import is fixed, fails with:

```
11. Runtime error (TypeErrorException): sequence item 1: expected bytes or byte array, str found
12. Traceback:
  line 508, in sync_request, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 549, in root, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 100, in _connect, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 70, in connect, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\classic.py"
  line 117, in _get_connection, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
  line 49, in script
  line 319, in dump, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\brine.py"
  line 235, in _send, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 266, in _send_request, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\protocol.py"
  line 195, in on_connect, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\core\service.py"
  line 43, in connect_channel, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 54, in connect_stream, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 93, in connect, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rpyc\utils\factory.py"
  line 36, in __init__, "C:\Users\pcuvil\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\ghpythonremote\connectors.py"
```

**Comment by pilcru** [comment]
async was renamed to async_, fixed in d288316.

IronPython 2.7.0 does not cast to bytes before joining a list into a bytes, which was fixed in 2.7.5, explaining the different behavior. The issue comes from the brine `_dump` methods not always returning bytes (strings instead), and so merging into the stream fails.
